#100 execuções do programa

./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
./a.out 2.2 >> time.dsf
